import js from '@eslint/js';
import tseslint from 'typescript-eslint';

/**
 * Lint configuration for Sprint 0.2.
 *
 * Type-aware rules are enabled for the TypeScript written in this sprint,
 * because the mistakes worth catching here (a floating promise in a message
 * handler, an unawaited transaction, an `any` smuggled past a boundary) are
 * invisible to a syntax-only pass.
 *
 * Generated code is not linted: it is regenerated by `pnpm generate`, so a
 * finding in it could not be fixed in a durable way.
 */
export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/dist-tests/**',
      'services/*/src/generated/**',
      'evidence/**',
      '.acceptance/**',
      // The approved customer UI is byte-locked and must not be rewritten.
      'design/**',
      'apps/customer-web/prototype/**',
      // Byte-frozen guard tests are executed by test:design-lock; lint must not
      // require edits to files the design-reference policy forbids changing.
      'tests/design/**',
      // F001-owned source is linted by eslint.f001.config.mjs in its own mandatory gate.
      // Do not apply a second, different global policy to the same files.
      'scripts/f001/**',
      'scripts/ownership/**',
      'tests/contracts/**',
      'tests/foundation/**',
      'tests/ownership/**',
      'docs/**',
    ],
  },

  js.configs.recommended,

  // TypeScript written in this sprint: full type-aware linting.
  {
    files: [
      'packages/*/src/**/*.ts',
      'services/*/src/**/*.ts',
      'apps/api-gateway/src/**/*.ts',
      'services/*/test/**/*.ts',
    ],
    extends: [...tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // A promise dropped on the floor in a consumer or relay silently loses a
      // message instead of failing, so this is an error rather than a warning.
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { fixStyle: 'inline-type-imports', disallowTypeAnnotations: false },
      ],
      '@typescript-eslint/require-await': 'error',
      // Prisma's generated model types are intentionally loose in places; an
      // unavoidable assertion must still be explicit rather than silent.
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      'no-console': 'off',
    },
  },

  // node:test returns a promise from `test()` that the runner owns; awaiting it
  // at the top level of a spec is wrong, not right. The rule is therefore off
  // for spec files only, and stays on everywhere a dropped promise would
  // actually lose work.
  {
    files: ['services/*/test/**/*.ts'],
    rules: {
      '@typescript-eslint/no-floating-promises': 'off',
    },
  },

  // Harness, scripts and tests: plain JavaScript modules run by Node directly.
  {
    files: ['scripts/**/*.mjs', 'tests/**/*.mjs'],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'module',
      globals: {
        process: 'readonly',
        console: 'readonly',
        Buffer: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        setImmediate: 'readonly',
        queueMicrotask: 'readonly',
        URL: 'readonly',
        AbortController: 'readonly',
        WeakSet: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['error', { argsIgnorePattern: '^_', caughtErrors: 'none' }],
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },
);
