import type { OwnerContract } from '../common/route';
import { parseNonNegativeMoney, type Money } from '../common/money';
import {
  PAYMENT_METHODS,
  WALLET_PAYMENT_METHODS,
  type PaymentMethod,
} from '../common/payment-method';
import { parsePrincipalRef, type PrincipalRef } from '../common/principal';
import { parsePage, parseRevision, type Page } from '../common/protocol';
import { parseUtc, type UtcTimestamp } from '../common/time';
import { ContractViolation, closed, oneOf, text, uuid } from '../common/wire';

/**
 * billing.v1 — owner: Billing service (Lane B).
 *
 * One payment record per confirmed booking, created by Billing from
 * `booking.confirmed.v2` (never by a client call). The record carries the
 * method chosen on the approved payment screen and the SERVER's view of money:
 *
 *   CASH_AFTER_SERVICE: CASH_DUE -> CASH_COLLECTED (reported by the field,
 *                       not company settlement) | CANCELLED
 *   SHAM_CASH / SYRIATEL_CASH: AWAITING_TRANSFER -> AWAITING_REVIEW (customer
 *                       submitted a transaction reference) -> PAID (finance
 *                       matched it against the wallet statement) | back to
 *                       AWAITING_TRANSFER with a review outcome | CANCELLED
 *
 * A customer action, receipt or proof NEVER makes a payment PAID. Transfer
 * instructions (payee, QR) are returned only when a real merchant account is
 * configured; until then `availability` is MERCHANT_NOT_CONFIGURED and no
 * instructions exist. Billing never invents a payee or QR payload.
 */
export const BILLING_V1 = {
  id: 'billing.v1',
  owner: 'billing',
  prefix: '/internal/v1/billing',
  routes: {
    getBookingPayment: {
      method: 'GET',
      path: '/bookings/:bookingId/payment',
      access: 'principal',
    },
    submitTransferProof: {
      method: 'POST',
      path: '/payments/:paymentId/transfer-proofs',
      access: 'principal',
      idempotent: true,
    },
    listReviewQueue: {
      method: 'GET',
      path: '/payments/review-queue',
      access: 'permission:billing.payments.verify',
      paged: true,
    },
    reviewTransfer: {
      method: 'POST',
      path: '/payments/:paymentId/review',
      access: 'permission:billing.payments.verify',
      idempotent: true,
    },
  },
  reasons: [
    'PAYMENT_NOT_AWAITING_TRANSFER',
    'PAYMENT_NOT_AWAITING_REVIEW',
    'TRANSFER_UNAVAILABLE',
    'TRANSACTION_REFERENCE_IN_USE',
    'SELF_REVIEW_FORBIDDEN',
  ],
} as const satisfies OwnerContract;

export const PAYMENT_STATES = [
  'CASH_DUE',
  'CASH_COLLECTED',
  'AWAITING_TRANSFER',
  'AWAITING_REVIEW',
  'PAID',
  'CANCELLED',
] as const;
export type PaymentState = (typeof PAYMENT_STATES)[number];

const CASH_STATES: readonly PaymentState[] = ['CASH_DUE', 'CASH_COLLECTED', 'CANCELLED'];
const WALLET_STATES: readonly PaymentState[] = [
  'AWAITING_TRANSFER',
  'AWAITING_REVIEW',
  'PAID',
  'CANCELLED',
];

export const TRANSFER_AVAILABILITY = ['AVAILABLE', 'MERCHANT_NOT_CONFIGURED'] as const;
export type TransferAvailability = (typeof TRANSFER_AVAILABILITY)[number];

export const REVIEW_REJECTION_REASONS = [
  'REFERENCE_NOT_FOUND',
  'AMOUNT_MISMATCH',
  'PAYEE_MISMATCH',
] as const;
export type ReviewRejectionReason = (typeof REVIEW_REJECTION_REASONS)[number];

/** Wallet transaction reference as typed by the customer from the wallet app. */
const TRANSACTION_REFERENCE = /^[A-Za-z0-9-]{4,64}$/;
/** Opaque reference into the reconciled wallet statement used by finance. */
const STATEMENT_REFERENCE = /^[A-Za-z0-9_.:-]{4,128}$/;
/** Transfer reference the customer puts in the wallet memo; generated by Billing. */
const PAYMENT_REFERENCE = /^WGP-[0-9A-HJKMNP-TV-Z]{10}$/;

export interface TransferInstructionsV1 {
  readonly payeeName: string;
  readonly payeeAccount: string;
  readonly paymentReference: string;
  /** Payload encoded in the wallet's own QR format; rendered by the client as-is. */
  readonly qrPayload: string;
  readonly expiresAt: UtcTimestamp;
}

export interface PaymentTransferV1 {
  readonly availability: TransferAvailability;
  /** Non-null exactly when availability is AVAILABLE. */
  readonly instructions: TransferInstructionsV1 | null;
}

export interface PaymentV1 {
  readonly paymentId: string;
  readonly bookingId: string;
  readonly revision: number;
  readonly method: PaymentMethod;
  readonly state: PaymentState;
  readonly amount: Money;
  readonly beneficiary: PrincipalRef;
  /** null for cash; non-null for wallet methods. */
  readonly transfer: PaymentTransferV1 | null;
  readonly proof: {
    readonly transactionReference: string;
    readonly submittedAt: UtcTimestamp;
  } | null;
  /** The most recent negative review, shown so the customer can correct the reference. */
  readonly lastRejection: {
    readonly reason: ReviewRejectionReason;
    readonly reviewedAt: UtcTimestamp;
  } | null;
  readonly paidAt: UtcTimestamp | null;
  readonly createdAt: UtcTimestamp;
  readonly updatedAt: UtcTimestamp;
}

export interface SubmitTransferProofRequestV1 {
  readonly expectedRevision: number;
  readonly transactionReference: string;
}

export type ReviewTransferRequestV1 =
  | {
      readonly expectedRevision: number;
      readonly decision: 'CONFIRM_RECEIVED';
      readonly statementReference: string;
    }
  | {
      readonly expectedRevision: number;
      readonly decision: 'REJECT';
      readonly rejectionReason: ReviewRejectionReason;
    };

/** Finance queue item: no customer contact, address or vehicle data. */
export interface ReviewQueueItemV1 {
  readonly paymentId: string;
  readonly bookingId: string;
  readonly revision: number;
  readonly method: PaymentMethod;
  readonly amount: Money;
  readonly transactionReference: string;
  readonly submittedAt: UtcTimestamp;
}

function transactionReference(value: unknown, path: string): string {
  return text(value, path, { max: 64, pattern: TRANSACTION_REFERENCE });
}

function transfer(value: unknown, path: string): PaymentTransferV1 {
  const v = closed(value, path, ['availability', 'instructions']);
  const availability = oneOf(v.availability, `${path}.availability`, TRANSFER_AVAILABILITY);
  if ((availability === 'AVAILABLE') !== (v.instructions !== null)) {
    throw new ContractViolation('INCONSISTENT_TRANSFER', `${path}.instructions`);
  }
  if (v.instructions === null) return { availability, instructions: null };
  const at = `${path}.instructions`;
  const i = closed(v.instructions, at, [
    'payeeName',
    'payeeAccount',
    'paymentReference',
    'qrPayload',
    'expiresAt',
  ]);
  return {
    availability,
    instructions: {
      payeeName: text(i.payeeName, `${at}.payeeName`, { max: 80 }),
      payeeAccount: text(i.payeeAccount, `${at}.payeeAccount`, { max: 64 }),
      paymentReference: text(i.paymentReference, `${at}.paymentReference`, {
        max: 14,
        pattern: PAYMENT_REFERENCE,
      }),
      qrPayload: text(i.qrPayload, `${at}.qrPayload`, { max: 1024 }),
      expiresAt: parseUtc(i.expiresAt, `${at}.expiresAt`),
    },
  };
}

export function parsePaymentV1(value: unknown, path = '$'): PaymentV1 {
  const v = closed(value, path, [
    'paymentId',
    'bookingId',
    'revision',
    'method',
    'state',
    'amount',
    'beneficiary',
    'transfer',
    'proof',
    'lastRejection',
    'paidAt',
    'createdAt',
    'updatedAt',
  ]);
  const method = oneOf(v.method, `${path}.method`, PAYMENT_METHODS);
  const state = oneOf(v.state, `${path}.state`, PAYMENT_STATES);
  const wallet = (WALLET_PAYMENT_METHODS as readonly PaymentMethod[]).includes(method);
  if (!(wallet ? WALLET_STATES : CASH_STATES).includes(state)) {
    throw new ContractViolation('STATE_NOT_ALLOWED_FOR_METHOD', `${path}.state`);
  }
  if (wallet !== (v.transfer !== null)) {
    throw new ContractViolation('INCONSISTENT_TRANSFER', `${path}.transfer`);
  }
  let proof: PaymentV1['proof'] = null;
  if (v.proof !== null) {
    if (!wallet) throw new ContractViolation('CASH_HAS_PROOF', `${path}.proof`);
    const p = closed(v.proof, `${path}.proof`, ['transactionReference', 'submittedAt']);
    proof = {
      transactionReference: transactionReference(
        p.transactionReference,
        `${path}.proof.transactionReference`,
      ),
      submittedAt: parseUtc(p.submittedAt, `${path}.proof.submittedAt`),
    };
  }
  if ((state === 'AWAITING_REVIEW' || state === 'PAID') && proof === null) {
    throw new ContractViolation('PROOF_REQUIRED', `${path}.proof`);
  }
  let lastRejection: PaymentV1['lastRejection'] = null;
  if (v.lastRejection !== null) {
    if (!wallet) throw new ContractViolation('CASH_HAS_REVIEW', `${path}.lastRejection`);
    const r = closed(v.lastRejection, `${path}.lastRejection`, ['reason', 'reviewedAt']);
    lastRejection = {
      reason: oneOf(r.reason, `${path}.lastRejection.reason`, REVIEW_REJECTION_REASONS),
      reviewedAt: parseUtc(r.reviewedAt, `${path}.lastRejection.reviewedAt`),
    };
  }
  const paidAt = v.paidAt === null ? null : parseUtc(v.paidAt, `${path}.paidAt`);
  if ((state === 'PAID') !== (paidAt !== null)) {
    throw new ContractViolation('INCONSISTENT_PAID_AT', `${path}.paidAt`);
  }
  return {
    paymentId: uuid(v.paymentId, `${path}.paymentId`),
    bookingId: uuid(v.bookingId, `${path}.bookingId`),
    revision: parseRevision(v.revision, `${path}.revision`),
    method,
    state,
    amount: parseNonNegativeMoney(v.amount, `${path}.amount`),
    beneficiary: parsePrincipalRef(v.beneficiary, `${path}.beneficiary`),
    transfer: v.transfer === null ? null : transfer(v.transfer, `${path}.transfer`),
    proof,
    lastRejection,
    paidAt,
    createdAt: parseUtc(v.createdAt, `${path}.createdAt`),
    updatedAt: parseUtc(v.updatedAt, `${path}.updatedAt`),
  };
}

export function parseSubmitTransferProofRequestV1(value: unknown): SubmitTransferProofRequestV1 {
  const v = closed(value, '$', ['expectedRevision', 'transactionReference']);
  return {
    expectedRevision: parseRevision(v.expectedRevision, '$.expectedRevision'),
    transactionReference: transactionReference(v.transactionReference, '$.transactionReference'),
  };
}

export function parseReviewTransferRequestV1(value: unknown): ReviewTransferRequestV1 {
  const decision = closed(
    value,
    '$',
    ['expectedRevision', 'decision'],
    ['statementReference', 'rejectionReason'],
  ).decision;
  if (decision === 'CONFIRM_RECEIVED') {
    const v = closed(value, '$', ['expectedRevision', 'decision', 'statementReference']);
    return {
      expectedRevision: parseRevision(v.expectedRevision, '$.expectedRevision'),
      decision,
      statementReference: text(v.statementReference, '$.statementReference', {
        max: 128,
        pattern: STATEMENT_REFERENCE,
      }),
    };
  }
  if (decision === 'REJECT') {
    const v = closed(value, '$', ['expectedRevision', 'decision', 'rejectionReason']);
    return {
      expectedRevision: parseRevision(v.expectedRevision, '$.expectedRevision'),
      decision,
      rejectionReason: oneOf(v.rejectionReason, '$.rejectionReason', REVIEW_REJECTION_REASONS),
    };
  }
  throw new ContractViolation('INVALID_ENUM', '$.decision');
}

export function parseReviewQueueItemV1(value: unknown, path = '$'): ReviewQueueItemV1 {
  const v = closed(value, path, [
    'paymentId',
    'bookingId',
    'revision',
    'method',
    'amount',
    'transactionReference',
    'submittedAt',
  ]);
  const method = oneOf(v.method, `${path}.method`, WALLET_PAYMENT_METHODS);
  return {
    paymentId: uuid(v.paymentId, `${path}.paymentId`),
    bookingId: uuid(v.bookingId, `${path}.bookingId`),
    revision: parseRevision(v.revision, `${path}.revision`),
    method,
    amount: parseNonNegativeMoney(v.amount, `${path}.amount`),
    transactionReference: transactionReference(
      v.transactionReference,
      `${path}.transactionReference`,
    ),
    submittedAt: parseUtc(v.submittedAt, `${path}.submittedAt`),
  };
}

export function parseReviewQueuePageV1(value: unknown, path = '$'): Page<ReviewQueueItemV1> {
  return parsePage(value, path, parseReviewQueueItemV1);
}
